---
sidebar: sidebar 
permalink: get-started/faq.html 
keywords: astra faq, astra frequently asked questions, what is astra, astra control, kubernetes, persistent volumes 
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas mais frequentes para o Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== Visão geral

As seções a seguir fornecem respostas a algumas perguntas adicionais que você pode encontrar ao usar o Astra Control Center. Para esclarecimentos adicionais, entre em Contato com o NetApp.com



== Acesso ao Astra Control Center

*Qual é a URL do Astra Control?*

O Astra Control Center usa autenticação local e uma URL específica para cada ambiente.

Para o URL, em um navegador, digite o nome de domínio totalmente qualificado (FQDN) definido no campo spec.astraAddress no arquivo Astra_control_center.yaml custom resource (CR) quando você instalou o Astra Control Center. O e-mail é o valor definido no campo spec.email no astra_control_center.yaml CR.



== Licenciamento

*Estou usando uma licença de avaliação. Como faço para mudar para a licença completa?*

Você pode facilmente mudar para uma licença completa obtendo o arquivo de licença NetApp (NLF) da NetApp.

*Passos*

. Na navegação à esquerda, selecione *conta* > *Licença*.
. Na visão geral da licença, à direita das informações da licença, selecione o menu Opções.
. Selecione *Substituir*.
. Navegue até o arquivo de licença que você baixou e selecione *Adicionar*.


*Estou usando uma licença de avaliação. Ainda posso gerenciar aplicativos?*

Sim, você pode testar a funcionalidade de gerenciamento de aplicativos com uma licença de avaliação (incluindo a licença de avaliação incorporada instalada por padrão). Não há diferença em recursos ou recursos entre uma licença de avaliação e uma licença completa; a licença de avaliação simplesmente tem uma vida útil mais curta. link:../concepts/licensing.html["Licenciamento"^]Consulte para obter mais informações.



== Registrando clusters do Kubernetes

*Eu preciso adicionar nós de trabalho ao meu cluster do Kubernetes depois de adicionar ao Astra Control. O que devo fazer?*

Novos nós de trabalho podem ser adicionados a pools existentes. Eles serão descobertos automaticamente pelo Astra Control. Se os novos nós não estiverem visíveis no Astra Control, verifique se os novos nós de trabalho estão executando o tipo de imagem suportado. Você também pode verificar a integridade dos novos nós de trabalho usando o `kubectl get nodes` comando.

*Como faço para desgerenciar corretamente um cluster?*

. link:../use/unmanage.html["Desgerenciar as aplicações do Astra Control"].
. link:../use/unmanage.html#stop-managing-compute["Desgerenciar o cluster a partir do Astra Control"].


*O que acontece com minhas aplicações e dados após a remoção do cluster Kubernetes do Astra Control?*

A remoção de um cluster do Astra Control não fará alterações na configuração do cluster (aplicações e storage persistente). Todos os snapshots ou backups do Astra Control feitos de aplicações nesse cluster não estarão disponíveis para restauração. Os backups de storage persistente criados pelo Astra Control permanecem no Astra Control, mas não estão disponíveis para restauração.


WARNING: Sempre remova um cluster do Astra Control antes de excluí-lo por meio de outros métodos. A exclusão de um cluster usando outra ferramenta enquanto ele ainda está sendo gerenciado pelo Astra Control pode causar problemas para sua conta Astra Control.

*O NetApp Astra Trident é desinstalado automaticamente de um cluster quando eu o desgerencio?* Quando você desgerencia um cluster do Astra Control Center, o Astra Trident não é desinstalado automaticamente do cluster. Para desinstalar o Astra Trident, você precisará https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Siga estas etapas na documentação do Astra Trident"^].



== Gerenciamento de aplicações

*O Astra Control pode implantar uma aplicação?*

O Astra Control não implanta aplicações. As aplicações precisam ser implantadas fora do Astra Control.

*O que acontece com as aplicações depois de parar de gerenciá-las do Astra Control?*

Quaisquer backups ou snapshots existentes serão excluídos. Aplicativos e dados permanecem disponíveis. As operações de gerenciamento de dados não estarão disponíveis para aplicativos não gerenciados ou backups ou snapshots que pertençam a eles.

*O Astra Control pode gerenciar uma aplicação que esteja em um storage que não seja da NetApp?*

Não. Embora o Astra Control possa descobrir aplicações que estão usando storage que não é NetApp, ele não pode gerenciar uma aplicação que esteja usando storage que não seja NetApp.

*Devo gerenciar o próprio Astra Control?*

O Astra Control Center não é mostrado por padrão como uma aplicação que pode ser gerenciada, mas é possível fazer backup e restaurar uma instância do Astra Control Center usando outra instância do Astra Control Center.

*Os pods não saudáveis afetam o gerenciamento de aplicativos?*

Não, a integridade dos pods não afeta o gerenciamento de aplicativos.



== Operações de gerenciamento de dados

*Meu aplicativo usa vários PVS. O Astra Control fará snapshots e backups desses PVS?*

Sim. Uma operação de snapshot em uma aplicação do Astra Control inclui snapshots de todos os PVS vinculados aos PVCs da aplicação.

*Posso gerenciar snapshots feitos pelo Astra Control diretamente por meio de uma interface ou storage de objetos diferente?*

Não. Os snapshots e backups feitos pelo Astra Control só podem ser gerenciados com o Astra Control.
